---
- hosts: all

  become: true
  tasks:
    - name: Get human-readable disk space information
      shell: df -h
      register: df_result

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_result

    - name: Debug the disk space output
      debug:
        msg: "Disk space information:\n{{ df_result.stdout }}"

    - name: Get size of /run
      shell: "df --block-size 1m /run --output=size | tail -1"
      register: shell_df_result

    - name: Set facts for /run tmpfs size
      set_fact:
        run_tmpfs_size_mb: "{{ shell_df_result.stdout | int }}"

    - name: Debug /run tmpfs size
      debug:
        var: run_tmpfs_size_mb

    - name: Send update completion notification
      mail:
        host: smtp.gmail.com
        port: 587
        username: workgcannon@gmail.com
        password: "xscj expv qrzi zbay"
        to: workgcannon@gmail.com
        subject: "Disk Space Usage"
        body: '{"content": "Disk space on {{ inventory_hostname }} is above 10%!"}'
      when: disk_usage.stdout[:-1]|int > 10
      vars:
        ansible_python_interpreter: /usr/bin/python3
      delegate_to: localhost
