---
- hosts: all

  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      changed_when: false

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Update Pi-hole
      command: pihole -up
      register: pihole_update_result
      changed_when: "'Everything is already up to date' not in pihole_update_result.stdout"

    - name: Display Pi-hole update results
      debug:
        var: pihole_update_result.stdout_lines
        
- name: Send update completion notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: workgcannon@gmail.com
    password: "xscj expv qrzi zbay"
    to: workgcannon@gmail.com
    subject: "Pi-hole update completed"
    body: "Updates have been applied to all Pi-hole instances.\n\n{{ pihole_update_result.stdout }}"
  when: pihole_update_result.changed
  no_log: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  delegate_to: localhost
